//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BudgetMasterIntactEntities : DbContext
    {
        public BudgetMasterIntactEntities()
            : base("name=BudgetMasterIntactEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<Census> Census1 { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<FacilityBudget> FacilityBudgets { get; set; }
        public virtual DbSet<FacilityBudgetGL> FacilityBudgetGLs { get; set; }
        public virtual DbSet<GeneralLedger> GeneralLedgers { get; set; }
        public virtual DbSet<GLAccountType> GLAccountTypes { get; set; }
        public virtual DbSet<IntactAcctPayTypeMap> IntactAcctPayTypeMaps { get; set; }
        public virtual DbSet<LaborExpenseGLGrp> LaborExpenseGLGrps { get; set; }
        public virtual DbSet<MonthTable> MonthTables { get; set; }
        public virtual DbSet<OtherExpens> OtherExpenses { get; set; }
        public virtual DbSet<OtherExpensesDependentGLAccount> OtherExpensesDependentGLAccounts { get; set; }
        public virtual DbSet<OtherExpensesFacilityGLCalcValue> OtherExpensesFacilityGLCalcValues { get; set; }
        public virtual DbSet<OtherExpensesGLAccount> OtherExpensesGLAccounts { get; set; }
        public virtual DbSet<OtherExpensesGLCalc> OtherExpensesGLCalcs { get; set; }
        public virtual DbSet<OtherExpensesGLCalcValueMaster> OtherExpensesGLCalcValueMasters { get; set; }
        public virtual DbSet<OtherExpensesPtoHoliday> OtherExpensesPtoHolidays { get; set; }
        public virtual DbSet<OtherRevenue> OtherRevenues { get; set; }
        public virtual DbSet<PayGrp> PayGrps { get; set; }
        public virtual DbSet<PayrollGLAccount> PayrollGLAccounts { get; set; }
        public virtual DbSet<PayType> PayTypes { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<ReportMonth> ReportMonths { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<vwFacilitiesByRegionAndState> vwFacilitiesByRegionAndStates { get; set; }
        public virtual DbSet<vwLaborNetHours_AdHoc> vwLaborNetHours_AdHoc { get; set; }
        public virtual DbSet<vwYtdNumDay> vwYtdNumDays { get; set; }
        public virtual DbSet<AllowedADUser> AllowedADUsers { get; set; }
    
        [DbFunction("BudgetMasterIntactEntities", "fn_Split")]
        public virtual IQueryable<fn_Split_Result> fn_Split(string sText, string sDelim)
        {
            var sTextParameter = sText != null ?
                new ObjectParameter("sText", sText) :
                new ObjectParameter("sText", typeof(string));
    
            var sDelimParameter = sDelim != null ?
                new ObjectParameter("sDelim", sDelim) :
                new ObjectParameter("sDelim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Split_Result>("[BudgetMasterIntactEntities].[fn_Split](@sText, @sDelim)", sTextParameter, sDelimParameter);
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnAtriumPayPeriodExport")]
        public virtual IQueryable<fnAtriumPayPeriodExport_Result> fnAtriumPayPeriodExport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnAtriumPayPeriodExport_Result>("[BudgetMasterIntactEntities].[fnAtriumPayPeriodExport]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnBudgetCensusByPayGrp")]
        public virtual IQueryable<fnBudgetCensusByPayGrp_Result> fnBudgetCensusByPayGrp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnBudgetCensusByPayGrp_Result>("[BudgetMasterIntactEntities].[fnBudgetCensusByPayGrp]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnBudgetCensusByPayType")]
        public virtual IQueryable<fnBudgetCensusByPayType_Result> fnBudgetCensusByPayType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnBudgetCensusByPayType_Result>("[BudgetMasterIntactEntities].[fnBudgetCensusByPayType]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusBudgetAdc")]
        public virtual IQueryable<fnCensusBudgetAdc_Result> fnCensusBudgetAdc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusBudgetAdc_Result>("[BudgetMasterIntactEntities].[fnCensusBudgetAdc]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusBudgetByPayGrpADC")]
        public virtual IQueryable<fnCensusBudgetByPayGrpADC_Result> fnCensusBudgetByPayGrpADC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusBudgetByPayGrpADC_Result>("[BudgetMasterIntactEntities].[fnCensusBudgetByPayGrpADC]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusBudgetByPayTypeADC")]
        public virtual IQueryable<fnCensusBudgetByPayTypeADC_Result> fnCensusBudgetByPayTypeADC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusBudgetByPayTypeADC_Result>("[BudgetMasterIntactEntities].[fnCensusBudgetByPayTypeADC]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusGLRevCrossTab")]
        public virtual IQueryable<fnCensusGLRevCrossTab_Result> fnCensusGLRevCrossTab()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusGLRevCrossTab_Result>("[BudgetMasterIntactEntities].[fnCensusGLRevCrossTab]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusGrossDays")]
        public virtual IQueryable<fnCensusGrossDays_Result> fnCensusGrossDays()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusGrossDays_Result>("[BudgetMasterIntactEntities].[fnCensusGrossDays]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusGrossDaysCrossTab")]
        public virtual IQueryable<fnCensusGrossDaysCrossTab_Result> fnCensusGrossDaysCrossTab()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusGrossDaysCrossTab_Result>("[BudgetMasterIntactEntities].[fnCensusGrossDaysCrossTab]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusGrossDaysCUBE")]
        public virtual IQueryable<fnCensusGrossDaysCUBE_Result> fnCensusGrossDaysCUBE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusGrossDaysCUBE_Result>("[BudgetMasterIntactEntities].[fnCensusGrossDaysCUBE]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusGrossDaysGLCrossTab")]
        public virtual IQueryable<fnCensusGrossDaysGLCrossTab_Result> fnCensusGrossDaysGLCrossTab()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusGrossDaysGLCrossTab_Result>("[BudgetMasterIntactEntities].[fnCensusGrossDaysGLCrossTab]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusGrossDaysStat")]
        public virtual IQueryable<fnCensusGrossDaysStat_Result> fnCensusGrossDaysStat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusGrossDaysStat_Result>("[BudgetMasterIntactEntities].[fnCensusGrossDaysStat]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnCensusGrossDaysSum")]
        public virtual IQueryable<fnCensusGrossDaysSum_Result> fnCensusGrossDaysSum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCensusGrossDaysSum_Result>("[BudgetMasterIntactEntities].[fnCensusGrossDaysSum]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnFacilitiesPayPeriodExport")]
        public virtual IQueryable<fnFacilitiesPayPeriodExport_Result> fnFacilitiesPayPeriodExport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnFacilitiesPayPeriodExport_Result>("[BudgetMasterIntactEntities].[fnFacilitiesPayPeriodExport]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnGLRevenueAccounts")]
        public virtual IQueryable<fnGLRevenueAccounts_Result> fnGLRevenueAccounts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnGLRevenueAccounts_Result>("[BudgetMasterIntactEntities].[fnGLRevenueAccounts]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnLaborGLAccounts")]
        public virtual IQueryable<fnLaborGLAccounts_Result> fnLaborGLAccounts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnLaborGLAccounts_Result>("[BudgetMasterIntactEntities].[fnLaborGLAccounts]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnLaborNetDollarsBase1")]
        public virtual IQueryable<fnLaborNetDollarsBase1_Result> fnLaborNetDollarsBase1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnLaborNetDollarsBase1_Result>("[BudgetMasterIntactEntities].[fnLaborNetDollarsBase1]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnLaborStat")]
        public virtual IQueryable<fnLaborStat_Result> fnLaborStat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnLaborStat_Result>("[BudgetMasterIntactEntities].[fnLaborStat]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnMonthlyLaborBudgetADC")]
        public virtual IQueryable<fnMonthlyLaborBudgetADC_Result> fnMonthlyLaborBudgetADC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnMonthlyLaborBudgetADC_Result>("[BudgetMasterIntactEntities].[fnMonthlyLaborBudgetADC]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpCalculatedGLparentChild")]
        public virtual IQueryable<fnOtherExpCalculatedGLparentChild_Result> fnOtherExpCalculatedGLparentChild(Nullable<int> i_intOtherExpensesCalcID)
        {
            var i_intOtherExpensesCalcIDParameter = i_intOtherExpensesCalcID.HasValue ?
                new ObjectParameter("i_intOtherExpensesCalcID", i_intOtherExpensesCalcID) :
                new ObjectParameter("i_intOtherExpensesCalcID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpCalculatedGLparentChild_Result>("[BudgetMasterIntactEntities].[fnOtherExpCalculatedGLparentChild](@i_intOtherExpensesCalcID)", i_intOtherExpensesCalcIDParameter);
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpCalcValueMaster")]
        public virtual IQueryable<fnOtherExpCalcValueMaster_Result> fnOtherExpCalcValueMaster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpCalcValueMaster_Result>("[BudgetMasterIntactEntities].[fnOtherExpCalcValueMaster]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpensesStatic")]
        public virtual IQueryable<fnOtherExpensesStatic_Result> fnOtherExpensesStatic()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpensesStatic_Result>("[BudgetMasterIntactEntities].[fnOtherExpensesStatic]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpFica")]
        public virtual IQueryable<fnOtherExpFica_Result> fnOtherExpFica()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpFica_Result>("[BudgetMasterIntactEntities].[fnOtherExpFica]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpFicaOriginal")]
        public virtual IQueryable<fnOtherExpFicaOriginal_Result> fnOtherExpFicaOriginal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpFicaOriginal_Result>("[BudgetMasterIntactEntities].[fnOtherExpFicaOriginal]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpMgtFeeCalc")]
        public virtual IQueryable<fnOtherExpMgtFeeCalc_Result> fnOtherExpMgtFeeCalc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpMgtFeeCalc_Result>("[BudgetMasterIntactEntities].[fnOtherExpMgtFeeCalc]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpPharmCalc")]
        public virtual IQueryable<fnOtherExpPharmCalc_Result> fnOtherExpPharmCalc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpPharmCalc_Result>("[BudgetMasterIntactEntities].[fnOtherExpPharmCalc]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpPtoHol")]
        public virtual IQueryable<fnOtherExpPtoHol_Result> fnOtherExpPtoHol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpPtoHol_Result>("[BudgetMasterIntactEntities].[fnOtherExpPtoHol]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpPtoHol_Original")]
        public virtual IQueryable<fnOtherExpPtoHol_Original_Result> fnOtherExpPtoHol_Original()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpPtoHol_Original_Result>("[BudgetMasterIntactEntities].[fnOtherExpPtoHol_Original]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpTherapyOthercalc")]
        public virtual IQueryable<fnOtherExpTherapyOthercalc_Result> fnOtherExpTherapyOthercalc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpTherapyOthercalc_Result>("[BudgetMasterIntactEntities].[fnOtherExpTherapyOthercalc]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpTherapyPartAcalc")]
        public virtual IQueryable<fnOtherExpTherapyPartAcalc_Result> fnOtherExpTherapyPartAcalc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpTherapyPartAcalc_Result>("[BudgetMasterIntactEntities].[fnOtherExpTherapyPartAcalc]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherExpTherapyPartBcalc")]
        public virtual IQueryable<fnOtherExpTherapyPartBcalc_Result> fnOtherExpTherapyPartBcalc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherExpTherapyPartBcalc_Result>("[BudgetMasterIntactEntities].[fnOtherExpTherapyPartBcalc]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnOtherRevenueTotal")]
        public virtual IQueryable<fnOtherRevenueTotal_Result> fnOtherRevenueTotal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOtherRevenueTotal_Result>("[BudgetMasterIntactEntities].[fnOtherRevenueTotal]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnRegionsPayPeriodExport")]
        public virtual IQueryable<fnRegionsPayPeriodExport_Result> fnRegionsPayPeriodExport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnRegionsPayPeriodExport_Result>("[BudgetMasterIntactEntities].[fnRegionsPayPeriodExport]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnRevenueTotal")]
        public virtual IQueryable<fnRevenueTotal_Result> fnRevenueTotal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnRevenueTotal_Result>("[BudgetMasterIntactEntities].[fnRevenueTotal]()");
        }
    
        [DbFunction("BudgetMasterIntactEntities", "fnTotalsExcelExport")]
        public virtual IQueryable<fnTotalsExcelExport_Result> fnTotalsExcelExport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnTotalsExcelExport_Result>("[BudgetMasterIntactEntities].[fnTotalsExcelExport]()");
        }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int Facility_Clone(string newFacilityNumber, string newFacilityShortName, string newFacilityName, Nullable<int> newFacilityRegionID, Nullable<int> newFacilityStateID, Nullable<float> newWageIncrease, Nullable<float> newMgmtFee, Nullable<bool> newRestrictFromDwFeed, Nullable<int> sourceFacilityID)
        {
            var newFacilityNumberParameter = newFacilityNumber != null ?
                new ObjectParameter("NewFacilityNumber", newFacilityNumber) :
                new ObjectParameter("NewFacilityNumber", typeof(string));
    
            var newFacilityShortNameParameter = newFacilityShortName != null ?
                new ObjectParameter("NewFacilityShortName", newFacilityShortName) :
                new ObjectParameter("NewFacilityShortName", typeof(string));
    
            var newFacilityNameParameter = newFacilityName != null ?
                new ObjectParameter("NewFacilityName", newFacilityName) :
                new ObjectParameter("NewFacilityName", typeof(string));
    
            var newFacilityRegionIDParameter = newFacilityRegionID.HasValue ?
                new ObjectParameter("NewFacilityRegionID", newFacilityRegionID) :
                new ObjectParameter("NewFacilityRegionID", typeof(int));
    
            var newFacilityStateIDParameter = newFacilityStateID.HasValue ?
                new ObjectParameter("NewFacilityStateID", newFacilityStateID) :
                new ObjectParameter("NewFacilityStateID", typeof(int));
    
            var newWageIncreaseParameter = newWageIncrease.HasValue ?
                new ObjectParameter("NewWageIncrease", newWageIncrease) :
                new ObjectParameter("NewWageIncrease", typeof(float));
    
            var newMgmtFeeParameter = newMgmtFee.HasValue ?
                new ObjectParameter("NewMgmtFee", newMgmtFee) :
                new ObjectParameter("NewMgmtFee", typeof(float));
    
            var newRestrictFromDwFeedParameter = newRestrictFromDwFeed.HasValue ?
                new ObjectParameter("NewRestrictFromDwFeed", newRestrictFromDwFeed) :
                new ObjectParameter("NewRestrictFromDwFeed", typeof(bool));
    
            var sourceFacilityIDParameter = sourceFacilityID.HasValue ?
                new ObjectParameter("SourceFacilityID", sourceFacilityID) :
                new ObjectParameter("SourceFacilityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Facility_Clone", newFacilityNumberParameter, newFacilityShortNameParameter, newFacilityNameParameter, newFacilityRegionIDParameter, newFacilityStateIDParameter, newWageIncreaseParameter, newMgmtFeeParameter, newRestrictFromDwFeedParameter, sourceFacilityIDParameter);
        }
    
        public virtual int Facility_DeleteByFacilityID(Nullable<int> facilityID)
        {
            var facilityIDParameter = facilityID.HasValue ?
                new ObjectParameter("FacilityID", facilityID) :
                new ObjectParameter("FacilityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Facility_DeleteByFacilityID", facilityIDParameter);
        }
    
        public virtual int IntactImport_ExportSelectedFacilities(string facilityNumbers)
        {
            var facilityNumbersParameter = facilityNumbers != null ?
                new ObjectParameter("FacilityNumbers", facilityNumbers) :
                new ObjectParameter("FacilityNumbers", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IntactImport_ExportSelectedFacilities", facilityNumbersParameter);
        }
    
        public virtual int OtherExpenses_PropagateAmount(Nullable<int> facilityID, Nullable<int> budgetID, Nullable<int> gLAccountIndex, Nullable<int> recordType, Nullable<decimal> amount)
        {
            var facilityIDParameter = facilityID.HasValue ?
                new ObjectParameter("FacilityID", facilityID) :
                new ObjectParameter("FacilityID", typeof(int));
    
            var budgetIDParameter = budgetID.HasValue ?
                new ObjectParameter("BudgetID", budgetID) :
                new ObjectParameter("BudgetID", typeof(int));
    
            var gLAccountIndexParameter = gLAccountIndex.HasValue ?
                new ObjectParameter("GLAccountIndex", gLAccountIndex) :
                new ObjectParameter("GLAccountIndex", typeof(int));
    
            var recordTypeParameter = recordType.HasValue ?
                new ObjectParameter("RecordType", recordType) :
                new ObjectParameter("RecordType", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OtherExpenses_PropagateAmount", facilityIDParameter, budgetIDParameter, gLAccountIndexParameter, recordTypeParameter, amountParameter);
        }
    
        public virtual int OtherRevenue_CalculateQAS(Nullable<decimal> averageDailyCensus, Nullable<int> facilityID, Nullable<int> budgetID, Nullable<int> monthID, Nullable<decimal> rate, Nullable<int> otherRevenueGLAccount)
        {
            var averageDailyCensusParameter = averageDailyCensus.HasValue ?
                new ObjectParameter("AverageDailyCensus", averageDailyCensus) :
                new ObjectParameter("AverageDailyCensus", typeof(decimal));
    
            var facilityIDParameter = facilityID.HasValue ?
                new ObjectParameter("FacilityID", facilityID) :
                new ObjectParameter("FacilityID", typeof(int));
    
            var budgetIDParameter = budgetID.HasValue ?
                new ObjectParameter("BudgetID", budgetID) :
                new ObjectParameter("BudgetID", typeof(int));
    
            var monthIDParameter = monthID.HasValue ?
                new ObjectParameter("MonthID", monthID) :
                new ObjectParameter("MonthID", typeof(int));
    
            var rateParameter = rate.HasValue ?
                new ObjectParameter("Rate", rate) :
                new ObjectParameter("Rate", typeof(decimal));
    
            var otherRevenueGLAccountParameter = otherRevenueGLAccount.HasValue ?
                new ObjectParameter("OtherRevenueGLAccount", otherRevenueGLAccount) :
                new ObjectParameter("OtherRevenueGLAccount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OtherRevenue_CalculateQAS", averageDailyCensusParameter, facilityIDParameter, budgetIDParameter, monthIDParameter, rateParameter, otherRevenueGLAccountParameter);
        }
    
        public virtual int spDropCreateTbl_IntactImportFile_Base1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDropCreateTbl_IntactImportFile_Base1");
        }
    
        public virtual int spDropCreateTbl_IntactImportFile_TEMP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDropCreateTbl_IntactImportFile_TEMP");
        }
    
        public virtual int spIntactImportCsvCreateFacility(string facility_Nb)
        {
            var facility_NbParameter = facility_Nb != null ?
                new ObjectParameter("Facility_Nb", facility_Nb) :
                new ObjectParameter("Facility_Nb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spIntactImportCsvCreateFacility", facility_NbParameter);
        }
    
        public virtual int spIntactImportCsvCreateFacilityAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spIntactImportCsvCreateFacilityAll");
        }
    
        public virtual int spIntactImportFile_Base1_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spIntactImportFile_Base1_Load");
        }
    
        public virtual int spIntactImportFile_Temp_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spIntactImportFile_Temp_Load");
        }
    }
}
