//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budget()
        {
            this.FacilityBudgets = new HashSet<FacilityBudget>();
        }
    
        public int BudgetID { get; set; }
        public string BudgetYr { get; set; }
        public short BudgetNb { get; set; }
        public bool BudgetCurrentYr { get; set; }
        public bool BudgetNextYr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilityBudget> FacilityBudgets { get; set; }
    }
}
