//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facility()
        {
            this.FacilityBudgets = new HashSet<FacilityBudget>();
            this.OtherExpensesFacilityGLCalcValues = new HashSet<OtherExpensesFacilityGLCalcValue>();
        }
    
        public int FacilityID { get; set; }
        public string FacilityNb { get; set; }
        public string FacilityShortNm { get; set; }
        public string FacilityNm { get; set; }
        public int RegionID { get; set; }
        public int StateID { get; set; }
        public Nullable<float> WageIncreasePercentage { get; set; }
        public float MgtFeeCalcPercent { get; set; }
        public bool RestrictFromDwFeed { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilityBudget> FacilityBudgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesFacilityGLCalcValue> OtherExpensesFacilityGLCalcValues { get; set; }
    }
}
