//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralLedger()
        {
            this.FacilityBudgetGLs = new HashSet<FacilityBudgetGL>();
            this.IntactAcctPayTypeMaps = new HashSet<IntactAcctPayTypeMap>();
            this.OtherExpensesPtoHolidays = new HashSet<OtherExpensesPtoHoliday>();
            this.OtherExpensesPtoHolidays1 = new HashSet<OtherExpensesPtoHoliday>();
            this.OtherExpensesDependentGLAccounts = new HashSet<OtherExpensesDependentGLAccount>();
            this.OtherExpensesDependentGLAccounts1 = new HashSet<OtherExpensesDependentGLAccount>();
            this.OtherExpensesGLAccounts = new HashSet<OtherExpensesGLAccount>();
            this.PayrollGLAccounts = new HashSet<PayrollGLAccount>();
            this.Census = new HashSet<Census>();
            this.OtherRevenues = new HashSet<OtherRevenue>();
        }
    
        public int GLAccountIndex { get; set; }
        public string GLAccountNb { get; set; }
        public string GLAccountNm { get; set; }
        public int GLAccountTypeID { get; set; }
        public string GLAccountSimpleNm { get; set; }
        public Nullable<int> OtherExpensesCalcID { get; set; }
        public string GLArTypeCd { get; set; }
        public string PayGrpCd { get; set; }
        public Nullable<int> LaborExpenseGLGrpID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilityBudgetGL> FacilityBudgetGLs { get; set; }
        public virtual GLAccountType GLAccountType { get; set; }
        public virtual OtherExpensesGLCalc OtherExpensesGLCalc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntactAcctPayTypeMap> IntactAcctPayTypeMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesPtoHoliday> OtherExpensesPtoHolidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesPtoHoliday> OtherExpensesPtoHolidays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesDependentGLAccount> OtherExpensesDependentGLAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesDependentGLAccount> OtherExpensesDependentGLAccounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesGLAccount> OtherExpensesGLAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollGLAccount> PayrollGLAccounts { get; set; }
        public virtual PayGrp PayGrp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Census> Census { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherRevenue> OtherRevenues { get; set; }
    }
}
