//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntactAcctPayTypeMap
    {
        public string GLAccountNb { get; set; }
        public string PayTypeCd { get; set; }
        public int GLAccountIndex { get; set; }
    
        public virtual GeneralLedger GeneralLedger { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
