//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthTable()
        {
            this.Census = new HashSet<Census>();
            this.OtherExpenses = new HashSet<OtherExpens>();
            this.OtherRevenues = new HashSet<OtherRevenue>();
            this.OtherExpensesFacilityGLCalcValues = new HashSet<OtherExpensesFacilityGLCalcValue>();
            this.PayrollGLAccounts = new HashSet<PayrollGLAccount>();
        }
    
        public int MonthID { get; set; }
        public short MonthNb { get; set; }
        public short NumDaysInMonth { get; set; }
        public string MonthNm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Census> Census { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpens> OtherExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherRevenue> OtherRevenues { get; set; }
        public virtual ReportMonth ReportMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesFacilityGLCalcValue> OtherExpensesFacilityGLCalcValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollGLAccount> PayrollGLAccounts { get; set; }
    }
}
