//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherExpensesGLCalc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtherExpensesGLCalc()
        {
            this.GeneralLedgers = new HashSet<GeneralLedger>();
            this.OtherExpensesGLCalcValueMasters = new HashSet<OtherExpensesGLCalcValueMaster>();
        }
    
        public int OtherExpensesCalcID { get; set; }
        public string CalcNm { get; set; }
        public short CalcCd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralLedger> GeneralLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesGLCalcValueMaster> OtherExpensesGLCalcValueMasters { get; set; }
    }
}
