//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherExpensesGLCalcValueMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtherExpensesGLCalcValueMaster()
        {
            this.OtherExpensesFacilityGLCalcValues = new HashSet<OtherExpensesFacilityGLCalcValue>();
            this.OtherExpensesGLCalcs = new HashSet<OtherExpensesGLCalc>();
        }
    
        public int CalcValueID { get; set; }
        public string CalcValueNm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesFacilityGLCalcValue> OtherExpensesFacilityGLCalcValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpensesGLCalc> OtherExpensesGLCalcs { get; set; }
    }
}
