//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherExpens
    {
        public int FacilityID { get; set; }
        public int BudgetID { get; set; }
        public int GLAccountIndex { get; set; }
        public int MonthID { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<decimal> DollarsPPD { get; set; }
    
        public virtual MonthTable MonthTable { get; set; }
        public virtual OtherExpensesGLAccount OtherExpensesGLAccount { get; set; }
    }
}
