//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherExpensesFacilityGLCalcValue
    {
        public int FacilityID { get; set; }
        public int CalcValueID { get; set; }
        public int MonthID { get; set; }
        public double CalcValue { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual MonthTable MonthTable { get; set; }
        public virtual OtherExpensesGLCalcValueMaster OtherExpensesGLCalcValueMaster { get; set; }
    }
}
