//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherExpensesGLAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtherExpensesGLAccount()
        {
            this.OtherExpenses = new HashSet<OtherExpens>();
        }
    
        public int FacilityID { get; set; }
        public int BudgetID { get; set; }
        public int GLAccountIndex { get; set; }
        public short RecordTypeCd { get; set; }
    
        public virtual FacilityBudget FacilityBudget { get; set; }
        public virtual GeneralLedger GeneralLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherExpens> OtherExpenses { get; set; }
    }
}
