//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollGLAccount
    {
        public int FacilityID { get; set; }
        public int BudgetID { get; set; }
        public int GLAccountIndex { get; set; }
        public double HoursPPD { get; set; }
        public decimal AverageWageRate { get; set; }
        public float HolidayPercentage { get; set; }
        public float PTOPercentage { get; set; }
        public byte WageIncreaseCd { get; set; }
        public int WageIncreaseMonth { get; set; }
        public bool BenefitCalculationFlag { get; set; }
    
        public virtual FacilityBudget FacilityBudget { get; set; }
        public virtual GeneralLedger GeneralLedger { get; set; }
        public virtual MonthTable MonthTable { get; set; }
    }
}
