//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumWebApp.Models.Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFacilitiesByRegionAndState
    {
        public int FacilityID { get; set; }
        public string StateCode { get; set; }
        public string RegionName { get; set; }
        public string FacilityNumber { get; set; }
        public string FacilityName { get; set; }
    }
}
